# Generated by Django 3.2.7 on 2022-03-29 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('curso', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=150)),
                ('cargo_atual', models.CharField(max_length=50)),
                ('empresa_atual', models.CharField(max_length=50)),
                ('trabalha_area', models.CharField(max_length=5)),
                ('ifb_ajudou', models.CharField(max_length=5)),
                ('grade_ifb', models.CharField(max_length=10)),
                ('curso_extra', models.CharField(max_length=10)),
                ('qual_curso_extra', models.CharField(max_length=30)),
                ('opiniao_curso_ifb', models.CharField(max_length=100)),
                ('pode_melhorar', models.CharField(max_length=100)),
                ('rede_social', models.CharField(max_length=100)),
                ('lattes', models.CharField(max_length=100)),
                ('validado', models.CharField(max_length=5)),
                ('contatos', models.ManyToManyField(related_name='_perfis_alunos_contatos_+', to='perfis.Alunos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('Superior', 'Superior (Bacharelado / Licenciatura)'), ('Superior', 'Superior (Tecnologia)'), ('Tecnico', 'Técnico (Integrado)'), ('Tecnico', 'Técnico(Subsequente)')], max_length=255)),
                ('campus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=255)),
                ('data_formatura', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=255)),
                ('alunos', models.ManyToManyField(related_name='turmaa', to='perfis.Alunos')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.curso')),
            ],
        ),
    ]
